name: tests
on: [push, pull_request]
jobs:
  busted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4
      - run: luarocks install busted
      - run: busted
